# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: do { code }
email: lincsanders@gmail.com
author: Lincoln Sanderson
description: > # this means to ignore newlines until "baseurl:"
  PHP/Ruby Programmer, Startup Lover, Startup Hater.
  Born in Australia, currently living in Stockholm, Sweden.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lincsanders.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: linc_sanders
github_username:  lincsanders
google_analytics: UA-86364636-1
disqus:
  shortname: lincsanders-github-io

host: 0.0.0.0
port: 3100

sass:
  load_paths:
    - assets
    - _sass

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
